### PR TITLE
Allow and ignore parsing optional field tags

### LINKED ISSUE #252: Thrift custom tags generate an error
You can add tags to the auto-generated thrift structs using the following format:
```
struct foo {
       1: required string Bar (go.tag = "some_tag:\"some_tag_value\"")
    }
```

However, with `thriftpy`, it generates this error:
```
thriftpy.parser.exc.ThriftGrammerError: Grammer error '('
```

### PR DESCRIPTION
**Pull request by misakwa**
Closes #252 

Added rules to ignore custom field tags.

### CODE REVIEW

**Comment by misakwa** [comment]
I'm unsure why the tests are failing. I couldn't get travis-ci to show the logs on both my fork and this build. Anyway to remedy this @lxyu?

**Comment by hit9** [comment]
Ref: https://github.com/apache/thrift/pull/128

**Comment by hit9** [comment]
Working on this.

**Comment by misakwa** [comment]
Thanks for working on this @hit9

**Pull request closed without merging**
