### PR TITLE
Add THttpServer and THttpClient for simple http support in thriftpy.

### PR DESCRIPTION
**Pull request by keitheis**
It refers to original [THttpServer and THttpClient implement in thrift 0.9.3](https://github.com/apache/thrift/tree/0.9.3/lib/py/src). Hope you enjoy it.

### CODE REVIEW

**Comment by djjekill** [comment]
Hi,

I've tested the http client implementation with Python 3.5.2 and I always had http Bad request response from my server.
The fact is that in http.py  after calling "putrequest('POST', self.path)" there's already a host header. So after calling "putheader('Host', self.host)" the request is sent with two host headers.
ex:
Host: webservice.domain.com:8080
Host: webservice.domain.com

I suggest to replace "putrequest('POST', self.path)" with "putrequest('POST', self.path, skip_host=True)"

Best regards

**Comment by keitheis** [comment]
@djjekill Thanks for the testing. It's updated by your suggestion.

**Comment by lxyu** [comment]
Thanks very much!

**Comment by keitheis** [comment]
Thank you!

**Pull request merged**
