### PR TITLE
Added DOCTEXT support for parsing thrift idl

### PR DESCRIPTION
**Pull request by mariusvniekerk**
This allows parsing documentation out of thrift DOCTEXT and creating python docstrings from it

### CODE REVIEW

**Comment by hit9** [comment]
Hi, Apache thrift dosen't support this feature. And, is there an example? I don't know how to map thrift comments to python object's docstring, it seems that there's no one-to-one mapping relationship.

**Comment by mariusvniekerk** [comment]
Sure.   I'll add some examples.  

The thrift compiler in Apache thrift master definately builds these in.  Essentially I'm adding them in so that I can move my service clients to python 3.

This branch also needs some cleaning with 2.6 and 3 it seems.   Didn't realize that 2.6 is still a target.

**Comment by mariusvniekerk** [comment]
This is where apache thrift assigns docstrings.

[`t_py_generator.cc` in apache compiler](https://github.com/apache/thrift/blob/28c1c19f913a4bee97a8309cf4b65914f705faea/compiler/cpp/src/generate/t_py_generator.cc#L2207)

Parsing information

[Function definition in `thrifty.yy` in apache compiler](https://github.com/apache/thrift/blob/4f4b15ba2b89aa553f982cd36b1cd70fd82a156e/compiler/cpp/src/thrifty.yy#L919)
[token definition in `thrifty.yy` in apache compiler](https://github.com/apache/thrift/blob/4f4b15ba2b89aa553f982cd36b1cd70fd82a156e/compiler/cpp/src/thrifty.yy#L101)

I am going to rebase this pull request.  Do you guys want me to amend one of the existing test thrift files?  Or should i just add a new dummy one?

**Comment by hit9** [comment]
Waiting apache thrift this feature released.

**Comment by mariusvniekerk** [comment]
Closing this guy until i can resolve the conflicts

**Pull request closed without merging**
