### PR TITLE
Namespace imports

### PR DESCRIPTION
**Pull request by misakwa**
- Remove suffix check from parser
- Add NamespacePathImporter

### CODE REVIEW

**Comment by misakwa** [comment]
pip downloads keep resetting on the ci.

**Comment by lxyu** [comment]
Let's follow the latest E402, I have fixed all violations in 6aa2aee :)

Can you please rebase the PR on the develop branch and remove the bee7174 commit?

**Comment by misakwa** [comment]
Sounds good! Should be fixed.

**Comment by lxyu** [comment]
Thanks for you contribution, while this feature didn't get a wide audiance so we'll temporary close it.

**Pull request closed without merging**
