### PR TITLE
modified tracker

### PR DESCRIPTION
**Pull request by maralla**
@wooparadog

### CODE REVIEW

**Comment by lxyu** [comment]
FYI, E402 addressed in 6aa2aeeccd11c8eabc601dbc533a65019c18e4b4

**Comment by wooparadog** [comment]
Good enough for now.

**Comment by wooparadog** [comment]
@lxyu You cherry picked the flake8 checks right? Then there shouldn't be too many conflicts.

**Comment by lxyu** [comment]
@wooparadog, it's actually, nope, some modification is different, for example the `noqa` on the 'monkey patch' is based on the style on PEP8's issue list.

It don't matters lot though, since it's tracker branch. We may fix it later.

**Pull request merged**
