### PR TITLE
add tracker support

### PR DESCRIPTION
**Pull request by maralla**
把type相关的单独放到了ttype.py里面,
每个client必须有单独的processor与之对应

@hit9 @wooparadog

### CODE REVIEW

**Comment by lxyu** [comment]
@maralla @wooparadog I don't really like this to be merged in the mainline version at this moment, it somehow looks like inventing an new simple and incomplete wheel.

Currently plan is 100% compat with Apache Thrift before v0.2, for the tracing function, I'd be happily accept it in the mainline only if it can be easily integrated with Zipkin or Finagle or some other mature projects.

**Comment by wooparadog** [comment]
@lxyu This is still 100% compatible with Apache Thrift. Tracking is an optional feature. We currently providing methods to actually trace calls between systems, as for Zipkin/Finagle integration, it should be done outside of thrift scope.

**Comment by maralla** [comment]
@wooparadog moved to [tracker](https://github.com/eleme/thriftpy/tree/tracker) branch

**Comment by lxyu** [comment]
@wooparadog yah, this needs a further discussion, generally speaking I have two concerns here:

1. by stay 100% compatible with Apache Thrift, I mean thriftpy currently only support:
 a. Apache Thrift features
 b. feature that makes it easier to use Apache Thrift features
 So I don't want to include this before v0.2 release, which is very close for now.

2. let's talk about the feature after v0.2 release.
 IMHO, most of thrift use env is stable production, if we gonna include tracing feature to thriftpy, the implementation should be more complete and mature.
 The PR for now is still in a very early stage of a brain storm, it needs more time to mature in every aspect.

**Comment by wooparadog** [comment]
@lxyu Yeah, my bad. We shouldn't unstable and unfinished work to master branch. I've told @maralla to open up a new branch, and will continue development their.

FYI: We are implementing tracking mechanism now. And hopefully, an initial version will be ready before Chinese new year.

**Comment by lxyu** [comment]
Glad to hear that! :)

BTW, I think we shouldn't mess the experiment feature with the stable features. So please do not directly add changes the core modules such as `thriftpy.thrift`.

I think may be we can add a `thriftpy.contrib` module for all the experimental features after v0.2. for example `thriftpy.contrib.tracing` would be ok, and put all changes in one place.

**Pull request closed without merging**
